import Head from 'next/head';
import About from '../../container/About';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio - Sobre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <About />
    </div>
  );
}
