import Head from 'next/head';
import Contact from '../../container/Contact';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio - Contatos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Contact />
    </div>
  );
}
