import Head from 'next/head';
import Projects from '../../container/Projects';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio - Projetos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Projects />
    </div>
  );
}
